#pragma once

#define RESOURCE_ICON                     101

#define RESOURCE_CURSOR_AMBER             103
#define RESOURCE_CURSOR_BLUE              104
#define RESOURCE_CURSOR_GREEN             105
#define RESOURCE_CURSOR_RED               106
#define RESOURCE_CURSOR_WHITE             107

#define RESOURCE_SCRIPT_MAIN              201
#define RESOURCE_SCRIPT_JSON              203
#define RESOURCE_SCRIPT_RPC               204
#define RESOURCE_SCRIPT_LOCALIZATION      205

#define RESOURCE_HUD_CHAT_SYSTEM_GFX      305
#define RESOURCE_HUD_VEHICLE_STATS_GFX    306
#define RESOURCE_HUD_PDA_BUY_GFX          307
#define RESOURCE_MENUS_LOADING_MP_GFX     308
#define RESOURCE_HUD_HIT_INDICATOR_GFX    309
#define RESOURCE_HUD_SPECTATE_GFX         310
#define RESOURCE_HUD_MP_RADIO_BUTTONS_GFX 311
#define RESOURCE_HUD_CHAT_SYSTEM_HR_GFX   312
#define RESOURCE_HUD_KILL_LOG_GFX         313

#define RESOURCE_MASTERS                  401
