#include "PCMDecoder.h"

STRUCT_INFO_BEGIN(SWaveHdr)
	STRUCT_VAR_INFO(RIFF, TYPE_ARRAY(4, TYPE_INFO(char)))
	STRUCT_VAR_INFO(dwSize, TYPE_INFO(uint32))
	STRUCT_VAR_INFO(WAVE, TYPE_ARRAY(4, TYPE_INFO(char)))
	STRUCT_VAR_INFO(fmt_, TYPE_ARRAY(4, TYPE_INFO(char)))
	STRUCT_VAR_INFO(dw16, TYPE_INFO(uint32))
	STRUCT_VAR_INFO(wOne_0, TYPE_INFO(uint16))
	STRUCT_VAR_INFO(wChnls, TYPE_INFO(uint16))
	STRUCT_VAR_INFO(dwSRate, TYPE_INFO(uint32))
	STRUCT_VAR_INFO(BytesPerSec, TYPE_INFO(uint32))
	STRUCT_VAR_INFO(wBlkAlign, TYPE_INFO(uint16))
	STRUCT_VAR_INFO(BitsPerSample, TYPE_INFO(uint16))
	STRUCT_VAR_INFO(DATA, TYPE_ARRAY(4, TYPE_INFO(char)))
	STRUCT_VAR_INFO(dwDSize, TYPE_INFO(uint32))
STRUCT_INFO_END(SWaveHdr)

