################################################################################
# Developer workflow running on pushes to the master branch and pull requests
################################################################################

name: Dev

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_32:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      bits: 32
      type: RelWithDebInfo
      sign: true

  build_64:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      bits: 64
      type: RelWithDebInfo
      sign: true

  upload:
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'crymp-net'
    needs:
      - build_32
      - build_64
    uses: ./.github/workflows/upload.yml
    secrets: inherit
    with:
      context: dev
      artifact_32: ${{ needs.build_32.outputs.artifact_name }}
      artifact_64: ${{ needs.build_64.outputs.artifact_name }}
