################################################################################
# Reusable workflow for uploading new executables to CryMP master server
################################################################################

name: Upload

on:
  workflow_call:
    inputs:
      context:
        description: Build type
        required: true
        type: string
      artifact_32:
        description: Name of 32-bit build artifact
        required: true
        type: string
      artifact_64:
        description: Name of 64-bit build artifact
        required: true
        type: string

jobs:
  crymp:
    runs-on: ubuntu-latest
    steps:
      - name: Download 32-bit build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_32 }}

      - name: Download 64-bit build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_64 }}

      - name: Upload to CryMP master server
        run: |
          set -e -o pipefail
          hmac_sha256()
          {
            openssl sha256 -hmac '${{ secrets.MASTER_NOTIFY_KEY }}' | sed 's/^.* //'
          }
          get_file_info()
          {
            echo "{\"name\": \"$(basename "$1")\", \"size\": $(stat -c %s "$1")}"
          }
          BASE_URL="http://crymp.org/api/v2_release"
          TIMESTAMP=$(date +%s)
          SIGNATURE=$(printf %s "$TIMESTAMP" | hmac_sha256)
          cat CryMP-Client32.exe CryMP-Client64.exe | curl --verbose --silent --show-error --fail-with-body \
            --http1.0 --request POST --data-binary @- \
            --header "Content-Type: application/octet-stream" \
            --header "x-body-signature: $(cat CryMP-Client32.exe CryMP-Client64.exe | hmac_sha256)" \
            --header "x-file-upload: [$(get_file_info CryMP-Client32.exe), $(get_file_info CryMP-Client64.exe)]" \
            "$BASE_URL?context=${{ inputs.context }}&time=$TIMESTAMP&commit=${{ github.sha }}&signature=$SIGNATURE" \
          | jq .
